---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: springboot-camel-ws
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: springboot-camel-ws@sha256:4e8a91e8e137124aab0ac574d6df8065db5beaea04cb3b808fe8549d72896d55
        namespace: camel-ws
      name: latest
